In [ ]:
import json

fd = open("result2.json",'r')
r = fd.read()
fd.close()
rec = json.loads(r)

In [ ]:
rec

{'1001': {'category': 'soap',
  'expdate': 'March/22',
  'name': 'Santoor',
  'price': 30,
  'quantity': 30},
 '1002': {'category': 'soap',
  'expdate': '3/22',
  'name': 'Lux',
  'price': 30,
  'quantity': 20},
 '1003': {'Quantity': 15,
  'category': 'soap',
  'expdate': '3/22',
  'name': 'cinthol',
  'price': 40,
  'quantity': 20},
 '1004': {'Quantity': 30,
  'category': 'colddrinks',
  'expdate': '3/22',
  'name': 'pepsi',
  'price': 20,
  'quantity': 35},
 '1005': {'Quantity': 30,
  'category': 'colddrinks',
  'expdate': '3/22',
  'name': 'coca-cola',
  'price': 20,
  'quantity': 35},
 '1006': {'Quantity': 40,
  'category': 'colddrinks',
  'expdate': '3/22',
  'name': 'maaza',
  'price': 25,
  'quantity': 45},
 '1007': {'category': 'colddrinks',
  'expdate': '3/22',
  'name': 'sprite',
  'price': 30,
  'quantity': 15},
 '1008': {'category': 'snacks',
  'expdate': '3/22',
  'name': 'lays',
  'price': 10,
  'quantity': 75},
 '1009': {'category': 'snacks',
  'expdate': '3/22',
  'name': 'Kurkure',
  'price': 20,
  'quantity': 85},
 '1010': {'category': 'snacks',
  'expdate': '3/22',
  'name': 'cheetos',
  'price': 15,
  'quantity': 60},
 '1011': {'category': 'snacks',
  'expdate': '3/22',
  'name': 'chedda',
  'price': 55,
  'quantity': 30},
 '1012': {'category': 'snacks',
  'expdate': '3/22',
  'name': 'cracks',
  'price': 10,
  'quantity': 50},
 '1013': {'category': 'biscuit',
  'expdate': '3/22',
  'name': 'parle-g',
  'price': 15,
  'quantity': 40},
 '1014': {'category': 'biscuit',
  'expdate': '3/22',
  'name': 'bourbon',
  'price': 20,
  'quantity': 40},
 '1015': {'category': 'biscuit',
  'expdate': '3/22',
  'name': 'magix',
  'price': 15,
  'quantity': 60},
 '1017': {'category': 'colddrinks',
  'expdate': '3/22',
  'name': 'fanta',
  'price': 20,
  'quantity': 50},
 '1018': {'category': 'colddrinks',
  'expdate': '3/22',
  'name': 'slice',
  'price': 70,
  'quantity': 40},
 '1019': {'category': 'colddrinks',
  'expdate': '3/22',
  'name': 'mirinda',
  'price': 25,
  'quantity': 30},
 '1020': {'category': 'colddrinks',
  'expdate': '3/22',
  'name': 'thumbs-up',
  'price': 30,
  'quantity': 5},
 '1021': {'category': 'icecream',
  'expdate': '3/22',
  'name': 'vanila',
  'price': 35,
  'quantity': 10},
 '1022': {'category': 'icecream',
  'expdate': '3/22',
  'name': 'strawberry',
  'price': 90,
  'quantity': 30},
 '1023': {'category': 'icecream',
  'expdate': '3/22',
  'name': 'butterscotch',
  'price': 150,
  'quantity': 25},
 '1024': {'category': 'icecream',
  'expdate': '3/22',
  'name': 'french vanila',
  'price': 250,
  'quantity': 40},
 '1025': {'category': 'icecream',
  'expdate': '3/22',
  'name': 'choclate',
  'price': 250,
  'quantity': 70},
 '1026': {'category': 'icecream',
  'expdate': '3/22',
  'name': 'neopolitan',
  'price': 325,
  'quantity': 50},
 '1027': {'category': 'clothing',
  'expdate': '3/25',
  'name': 'raymond',
  'price': 700,
  'quantity': 50},
 '1028': {'category': 'clothing',
  'expdate': '3/25',
  'name': 'jelly kelly',
  'price': 950,
  'quantity': 75},
 '1029': {'category': 'clothing',
  'expdate': '3/25',
  'name': 'gucci',
  'price': 800,
  'quantity': 60},
 '1030': {'category': 'clothing',
  'expdate': '3/25',
  'name': 'prada',
  'price': 1000,
  'quantity': 100}}

In [ ]:
import time 
time.ctime()


id = int(input("Enter Product ID : ")) 
quant = int(input("Enter the quantity : "))
st = str(id)
for i in st:
    if st in rec and quant < rec[st]['quantity']:
        print("WELCOME",)
        
        print("Product ID :",(st))
        print("Product :",(rec[st]["name"]))
        print("Category: ",(rec[st]["category"]))
        print("Price: ",(rec[st]["price"]))
        print("Quantity: ",(quant))
        print("Expiry Date: ",(rec[st]["expdate"])) 
        print("------------------------")
        print("Billing Amout: ", quant * (rec[st]["price"]))
        (rec[st]["Quantity"]) = (rec[st]["quantity"]) - quant
        print(time.ctime())
        print("*")
        break


    else: 
        print("Sorry, the product ID or quantity does not exist. Enter a valid product ID or quantity .")
        break

Enter Product ID : 1005
Enter the quantity : 5
WELCOME
Product ID : 1005
Product : coca-cola
Category:  colddrinks
Price:  20
Quantity:  5
Expiry Date:  3/22
------------------------
Billing Amout:  100
Sun Sep  5 17:53:02 2021
*

In [ ]:
rec
js = json.dumps(rec)
fd = open("result2.json",'w')
fd.write(js)
fd.close()
rec

{'1001': {'category': 'soap',
  'expdate': 'March/22',
  'name': 'Santoor',
  'price': 30,
  'quantity': 30},
 '1002': {'category': 'soap',
  'expdate': '3/22',
  'name': 'Lux',
  'price': 30,
  'quantity': 20},
 '1003': {'Quantity': 18,
  'category': 'soap',
  'expdate': '3/22',
  'name': 'cinthol',
  'price': 40,
  'quantity': 20},
 '1004': {'Quantity': 30,
  'category': 'colddrinks',
  'expdate': '3/22',
  'name': 'pepsi',
  'price': 20,
  'quantity': 35},
 '1005': {'Quantity': 30,
  'category': 'colddrinks',
  'expdate': '3/22',
  'name': 'coca-cola',
  'price': 20,
  'quantity': 35},
 '1006': {'Quantity': 40,
  'category': 'colddrinks',
  'expdate': '3/22',
  'name': 'maaza',
  'price': 25,
  'quantity': 45},
 '1007': {'category': 'colddrinks',
  'expdate': '3/22',
  'name': 'sprite',
  'price': 30,
  'quantity': 15},
 '1008': {'category': 'snacks',
  'expdate': '3/22',
  'name': 'lays',
  'price': 10,
  'quantity': 75},
 '1009': {'category': 'snacks',
  'expdate': '3/22',
  'name': 'Kurkure',
  'price': 20,
  'quantity': 85},
 '1010': {'category': 'snacks',
  'expdate': '3/22',
  'name': 'cheetos',
  'price': 15,
  'quantity': 60},
 '1011': {'category': 'snacks',
  'expdate': '3/22',
  'name': 'chedda',
  'price': 55,
  'quantity': 30},
 '1012': {'category': 'snacks',
  'expdate': '3/22',
  'name': 'cracks',
  'price': 10,
  'quantity': 50},
 '1013': {'category': 'biscuit',
  'expdate': '3/22',
  'name': 'parle-g',
  'price': 15,
  'quantity': 40},
 '1014': {'category': 'biscuit',
  'expdate': '3/22',
  'name': 'bourbon',
  'price': 20,
  'quantity': 40},
 '1015': {'category': 'biscuit',
  'expdate': '3/22',
  'name': 'magix',
  'price': 15,
  'quantity': 60},
 '1017': {'category': 'colddrinks',
  'expdate': '3/22',
  'name': 'fanta',
  'price': 20,
  'quantity': 50},
 '1018': {'category': 'colddrinks',
  'expdate': '3/22',
  'name': 'slice',
  'price': 70,
  'quantity': 40},
 '1019': {'category': 'colddrinks',
  'expdate': '3/22',
  'name': 'mirinda',
  'price': 25,
  'quantity': 30},
 '1020': {'category': 'colddrinks',
  'expdate': '3/22',
  'name': 'thumbs-up',
  'price': 30,
  'quantity': 5},
 '1021': {'category': 'icecream',
  'expdate': '3/22',
  'name': 'vanila',
  'price': 35,
  'quantity': 10},
 '1022': {'category': 'icecream',
  'expdate': '3/22',
  'name': 'strawberry',
  'price': 90,
  'quantity': 30},
 '1023': {'category': 'icecream',
  'expdate': '3/22',
  'name': 'butterscotch',
  'price': 150,
  'quantity': 25},
 '1024': {'category': 'icecream',
  'expdate': '3/22',
  'name': 'french vanila',
  'price': 250,
  'quantity': 40},
 '1025': {'category': 'icecream',
  'expdate': '3/22',
  'name': 'choclate',
  'price': 250,
  'quantity': 70},
 '1026': {'category': 'icecream',
  'expdate': '3/22',
  'name': 'neopolitan',
  'price': 325,
  'quantity': 50},
 '1027': {'category': 'clothing',
  'expdate': '3/25',
  'name': 'raymond',
  'price': 700,
  'quantity': 50},
 '1028': {'category': 'clothing',
  'expdate': '3/25',
  'name': 'jelly kelly',
  'price': 950,
  'quantity': 75},
 '1029': {'category': 'clothing',
  'expdate': '3/25',
  'name': 'gucci',
  'price': 800,
  'quantity': 60},
 '1030': {'category': 'clothing',
  'expdate': '3/25',
  'name': 'prada',
  'price': 1000,
  'quantity': 100}}

In [ ]:
sales = {'Product sold' : (rec[st]['name']), 'Quantity sold' : quant, 'Total Bill': quant * (rec[st]["price"])}

In [ ]:
            

sales[(len(sales)+1)] = {'Product sold' : (rec[st]['name']), 'Quantity sold' : quant, 'Total Bill': quant * (rec[st]["price"])}            

import json
j = json.dumps(sales)

fd = open("sales.json",'w')
fd.write(j)
fd.close()  

fd = open("sales.json",'r')
r = fd.read()
fd.close()
sales = json.loads(r)

sales

{'4': {'Product sold': 'cinthol', 'Quantity sold': 5, 'Total Bill': 200},
 '5': {'Product sold': 'cinthol', 'Quantity sold': 2, 'Total Bill': 80},
 '6': {'Product sold': 'coca-cola', 'Quantity sold': 5, 'Total Bill': 100},
 'Product sold': 'cinthol',
 'Quantity sold': 5,
 'Total Bill': 200}